[project]
name = "project-penney"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "timmyc181", email = "timothy.j.cleveland1@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "seaborn>=0.13.2",
]

[project.scripts]
project-penney = "project_penney:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
